# Generated by Django 5.2.7 on 2025-11-03 11:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
                ('resource_type', models.CharField(choices=[('product', 'PRODUCT'), ('user', 'USER'), ('order', 'ORDER'), ('live', 'LIVE'), ('system', 'SYSTEM'), ('content', 'CONTENT'), ('report', 'REPORT'), ('role', 'ROLE')], help_text='资源类型', max_length=50)),
                ('action_type', models.CharField(choices=[('view', 'VIEW'), ('create', 'CREATE'), ('update', 'UPDATE'), ('delete', 'DELETE'), ('import', 'IMPORT'), ('export', 'EXPORT'), ('approve', 'APPROVE'), ('reject', 'REJECT')], help_text='操作类型', max_length=50)),
                ('description', models.CharField(blank=True, help_text='权限描述', max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资源权限',
                'verbose_name_plural': '资源权限',
                'unique_together': {('resource_type', 'action_type')},
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.TextField(blank=True, null=True, verbose_name='权限组描述')),
                ('created_at', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='更新时间')),
                ('resource_permissions', models.ManyToManyField(blank=True, help_text='角色组拥有的资源权限', related_name='permission_groups', to='users.resourcepermission')),
            ],
            options={
                'verbose_name': '权限组',
                'verbose_name_plural': '权限组管理',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('role', models.CharField(choices=[('user', '普通用户'), ('admin', '管理员')], default='user', max_length=10, verbose_name='角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='用户所属的权限组', related_name='user_set', related_query_name='user', to='users.permissiongroup', verbose_name='权限组')),
                ('permission_groups', models.ManyToManyField(blank=True, help_text='用户所属的角色组', related_name='users', to='users.permissiongroup')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='用户拥有的具体权限', related_name='user_set', related_query_name='user', to='users.resourcepermission', verbose_name='用户权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
