# Generated by Django 5.2.7 on 2025-11-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='服务的唯一标识符', max_length=100, unique=True, verbose_name='服务名称')),
                ('description', models.TextField(blank=True, help_text='服务的详细描述信息', null=True, verbose_name='服务描述')),
                ('secret_hash', models.CharField(blank=True, help_text='服务密钥的哈希值，用于验证服务身份', max_length=255, null=True, verbose_name='服务密钥哈希')),
                ('is_enabled', models.BooleanField(default=True, help_text='控制服务是否可以进行身份认证', verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务管理',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='data_permission',
            field=models.CharField(choices=[('all', '全部数据'), ('own', '自己创建的数据')], default='own', max_length=10, verbose_name='数据权限'),
        ),
    ]
