# Generated by Django 5.2.7 on 2025-11-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service_user_data_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcepermission',
            name='action_type',
            field=models.CharField(choices=[('查看', 'VIEW'), ('创建', 'CREATE'), ('更新', 'UPDATE'), ('删除', 'DELETE'), ('导入', 'IMPORT'), ('导出', 'EXPORT'), ('审批', 'APPROVE'), ('拒绝', 'REJECT')], help_text='操作类型', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcepermission',
            name='resource_type',
            field=models.CharField(choices=[('商品', 'PRODUCT'), ('用户', 'USER'), ('订单', 'ORDER'), ('直播', 'LIVE'), ('系统', 'SYSTEM'), ('内容', 'CONTENT'), ('报表', 'REPORT'), ('角色', 'ROLE')], help_text='资源类型', max_length=50),
        ),
    ]
